---
output:
  html_document:
    css: "W:\\RDA Team\\R\\cc_brandguide.css"
---

<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)

#### Load libraries ####
library(usethis)
library(highcharter)
library(tidyverse)
library(sf)
library(leaflet)
library(sp)
library(htmltools) # for html escape
library(magrittr)
library(flextable)

library(htmlwidgets)


#### Add database connection ####
source("W:\\RDA Team\\R\\credentials_source.R")

con <- connect_to_db("eci_lb_ripa")

## Source the Chart Template

source("W:/Project/ECI/LB RIPA/R/chart_functions.R")
```

```{r bubblepop1, echo=FALSE}
##### Bubble Chart - stop rates per 1K by race for LB #####
# add a comma to stop count

# Apply Chart
report_stoprates_race_person <- dbGetQuery(con, "SELECT * FROM data.report_stoprates_race_person")  %>%filter(race!="total")


fx_barbubblechart(

  db=report_stoprates_race_person, #name of dataframe

  order_var=report_stoprates_race_person$stop_rate_per1k, #variable you're sorting by

  x='race_label_short', # x or independent variables

  y='stop_rate_per1k', # y or dependent variable

  z='stop_count',

  top_finding=paste0("LBPD stops Black, NHPI, and SSWANA people at higher rates than other community members."), # this is the top finding from the chart that gets used like a title

  chart_title= paste0("Number of Officer-initiated Stops per 1K of Same Population by Race and Ethnicity"), # this is the more standard chart title that gets used as a subtitle

  tooltip_text="For every 1K <b>{point.race_label_long:.1f}</b> people in Long Beach, LBPD stopped <b>{point.stop_rate_per1k:.1f}</b> people perceived as <b>{point.race_label_long:.1f}</b>, a total of <b>{point.stop_count:,0f}</b> people.", # customize your tooltip as a statement, calling out rate and count


  chart_caption = paste0(racenote,"<br>", sourcenote, "<br>","Analysis for all officer-initiated stops.","<br><br>"), # if necessary add a method note between the racenote and sourcenote with a line break, use racenote if graph includes data by race, and always use sourcenote. Each of these are standard objects across all charts

  yaxis_label = "''", #format for your y axis labels
   export_data_label=list(pointFormat='{point.stop_rate_per1k:.1f} per 1K')
)

invisible(dbDisconnect(con))
```

<script>
  document.querySelectorAll('.highchart').forEach((e) => {
    e.style.width = '100%';
  })
  document.querySelectorAll('.highchart').forEach((e) => {
    e.style.height = '100%';
  })
</script>
