---
output:
  html_document:
    css: "W:\\RDA Team\\R\\cc_brandguide.css"
---

<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)

#### Load libraries ####
library(usethis)
library(highcharter)
library(tidyverse)
library(sf)
library(leaflet)
library(sp)
library(htmltools) # for html escape
library(magrittr)
library(flextable)

library(htmlwidgets)


#### Add database connection ####
source("W:\\RDA Team\\R\\credentials_source.R")

con <- connect_to_db("eci_lb_ripa")

## Source the Chart Template

source("W:/Project/ECI/LB RIPA/R/chart_functions.R")
```


```{r bubble3, echo=FALSE}
##### Bubble Chart - unfounded searches by race for traffic violations % #####

report_hitrates_race_person <- dbGetQuery(con, "SELECT * FROM data.report_hitrates_race_person") 
report_hitrates_race_person<-report_hitrates_race_person%>%filter(race!="total")

# Apply Chart

fx_barbubblechart(

  db=report_hitrates_race_person, #name of dataframe

  order_var=report_stoprates_race_person$hit_rates, #variable you're sorting by

  x='race_label_short', # x or independent variables

  y='hit_rates', # y or dependent variable

  z='evidence_not_found',

 top_finding=paste0("Most searches LBPD conducts during traffic stops lead to no evidence or contraband found."), # this is the top finding from the chart that gets used like a title


   chart_title= paste0("Searches with No Contraband or Evidence Found among Traffic Stops by Race"), # this is the more standard chart title that gets used as a subtitle


  tooltip_text="For every 100 searches done during traffic stops of people perceived as <b>{point.race_label_long}</b>, LBPD did not find contraband/evidence in <b>{point.hit_rates:.0f}</b> stops,  a total of <b>{point.evidence_not_found:.0f}</b> unnecessary searches.", # customize your tooltip as a statement, calling out rate and count


    chart_caption = paste0(racenote,"<br>", sourcenote, "<br>", "Analysis for all officer-initiated traffic stops where a search occurred."), # if necessary add a method note between the racenote and sourcenote with a line break, use racenote if graph includes data by race, and always use sourcenote. Each of these are standard objects across all charts


 yaxis_label = "''", #format for your y axis labels
  export_data_label=list(pointFormat='{point.hit_rates:.1f}%') # format for your data labels on export images
)

invisible(dbDisconnect(con))

```

<script>
  widg = document.getElementsByClassName('html-widget'); //find widgets
  for (let i = 0; i < widg.length; i++) { //loop through
    document.getElementsByClassName('highchart')[i].style.width = '100%'; //adjust width
    document.getElementsByClassName('highchart')[i].style.height = '100%'; //adjust height
  }
</script>